[build]
  publish = "dist"
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  targetPort = 3001
  publish = "dist"

[build.environment]
  MONGODB_URI = "mongodb+srv://onurbenn:P93qRG%40s9v-y9Le@trihonorcluster.dq8qfba.mongodb.net/digilibrary?retryWrites=true&w=majority"

[dev.environment]
  MONGODB_URI = "mongodb+srv://onurbenn:P93qRG%40s9v-y9Le@trihonorcluster.dq8qfba.mongodb.net/digilibrary?retryWrites=true&w=majority"
  GOOGLE_BOOKS_API_KEY = "AIzaSyAHQQncjxUWuh80mhD1ucIEFOyzS1XYVXc"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200