[dev]
  framework = "vite"
  targetPort = 3000  # Vite'in çalıştığı port
  port = 3001        # Netlify Dev'in çalıştığı port

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200