[build]
  publish = "dist"
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  targetPort = 3001  # ⬅️ Bu satırı ekle!
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200