[build]
  publish = "dist"
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  targetPort = 3001
  publish = "dist"

[build.environment]
  MONGODB_URI = "your_mongodb_connection_string_here"

[dev.environment]
  MONGODB_URI = "your_mongodb_connection_string_here"
  GOOGLE_BOOKS_API_KEY = "your_google_books_api_key_here"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200